Repository n2n2dev/n2n2-react-native, pull requests merged in 2021-07, with the labels that each got.

#39 Fix gifs modal styling
  package.json
  src/components/chat/giphy/footer.tsx
  src/components/chat/giphy/header.tsx
  src/components/chat/giphy/index.tsx
  src/components/chat/giphy/styles.ts
  yarn.lock
Labels: Type: Enhancement 🔧

#58 Chore: Add Issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/new-feature.md
Labels: Type: Documentation 📑

#73 Fix audio
  src/components/Tribes/Tribe/Media/MediaItem.tsx
  src/components/chat/audioHelpers.ts
  src/components/chat/bottomBar.tsx
  src/components/chat/msg/audioPlayer.tsx
  src/components/chat/msg/hooks.ts
  src/components/chat/msg/mediaMsg.tsx
  src/components/chat/msgList.tsx
Labels: Type: Bug 🐞

#77 Add rumble video
  package.json
  src/components/chat/msg/rumbleVideo.tsx
  src/components/chat/msg/textMsg.tsx
  yarn.lock
Labels: Type: Enhancement 🔧
